# Generated by Django 6.0 on 2025-12-15 06:05

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import uuid
import wts_app.models.documents
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightParty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Copyright parties',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polling_date', models.DateField()),
                ('polls_close', models.DateTimeField()),
                ('election_type', models.CharField(choices=[('g', 'General'), ('b', 'By-election')], default='g', max_length=1)),
                ('name', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinisterialPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.TextField(blank=True, null=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20, unique=True)),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('party_leader_role', models.TextField(default='Leader')),
                ('party_leader_role_plural', models.TextField(default='Leaders')),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='PersistentVotingPlace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wts_app.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('categories', models.ManyToManyField(to='wts_app.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='wts_app.category')),
                ('documents', models.ManyToManyField(to='wts_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResultVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.election')),
            ],
            options={
                'unique_together': {('election', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ElectionElectorate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.TextField()),
                ('accepting_candidate_votes', models.BooleanField(default=True)),
                ('results_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.electionresultversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('results_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.electionresultversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionVotingPlace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('physical_electorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.electionelectorate')),
                ('results_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.electionresultversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Electorate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('electorate_type', models.CharField(choices=[('general', 'General'), ('maori', 'Māori')], default='general', max_length=10)),
                ('status', models.CharField(choices=[('current', 'Current'), ('retiring', 'Retiring'), ('new', 'New'), ('former', 'Former'), ('renamed', 'Renamed')], default='current', max_length=10)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('region', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('replaced', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement', to='wts_app.electorate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='electionelectorate',
            name='electorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.electorate'),
        ),
        migrations.CreateModel(
            name='ElectorateBoundarySet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electorate_boundary_sets', to='wts_app.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='election',
            name='boundary_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.electorateboundaryset'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.TextField()),
                ('file_description', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('file_type', models.CharField(max_length=255)),
                ('original_link_alive', models.BooleanField(default=True)),
                ('original_link_last_checked', models.DateTimeField(blank=True, null=True)),
                ('original_md5', models.CharField(blank=True, default='', max_length=32)),
                ('stored_md5', models.CharField(blank=True, default='', max_length=32)),
                ('file', models.FileField(storage=wts_app.models.documents.select_storage, upload_to=wts_app.models.documents.upload_to)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('copyright_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_files', to='wts_app.copyrightparty')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='wts_app.document')),
                ('licence_grantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licensed_files', to='wts_app.copyrightparty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectorateBoundary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('electorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.electorate')),
                ('boundary_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.electorateboundaryset')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electorate_boundaries', to='wts_app.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GazetteNotice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=255, unique=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gazette_notices', to='wts_app.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='electorateboundaryset',
            name='gazette_notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.gazettenotice'),
        ),
        migrations.AddField(
            model_name='election',
            name='gazette_notices',
            field=models.ManyToManyField(blank=True, to='wts_app.gazettenotice'),
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('licence_url', models.URLField(blank=True, null=True)),
                ('parent_licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.licence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='file',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.licence'),
        ),
        migrations.CreateModel(
            name='Parliament',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.election')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionParty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('results_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.electionresultversion')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.party')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='wts_app.file')),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PartyAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.party')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryAffiliation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elected_date', models.DateField(blank=True, null=True)),
                ('sworn_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fallback_electorate_slug', models.TextField(blank=True, null=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('end_reason', models.CharField(blank=True, choices=[('e93_55_1_a', 'Electoral Act 1993, s 55(1)(a): Non-attendance'), ('e93_55_1_b', 'Electoral Act 1993, s 55(1)(b): Allegiance to foreign state'), ('e93_55_1_c', 'Electoral Act 1993, s 55(1)(c): Subject or citizen of foreign state'), ('e93_55_1_ca', 'Electoral Act 1993, s 55(1)(ca): Cessation of New Zealand citizenship'), ('e93_55_1_cb_i', 'Electoral Act 1993, s 55(1)(cb)(i): Candidate in foreign Parliamentary election'), ('e93_55_1_cb_ii', 'Electoral Act 1993, s 55(1)(cb)(ii): Candidate in foreign governing body election'), ('e93_55_1_d', 'Electoral Act 1993, s 55(1)(d): Serious conviction or corruption'), ('e93_55_1_e', 'Electoral Act 1993, s 55(1)(e): Became public servant'), ('e93_55_1_ea', 'Electoral Act 1993, s 55(1)(ea): Appointed as electoral official'), ('e93_55_1_f', 'Electoral Act 1993, s 55(1)(f): Resignation'), ('e93_55_1_f_by', 'Electoral Act 1993, s 55(1)(f): Resignation (successful constituency candidate at by-election)'), ('e93_55_1_fa', 'Electoral Act 1993, ss 55(1)(fa) and 55A: Cessation of party membership'), ('e93_55_1_g', 'Electoral Act 1993, s 55(1)(g): Election voided on petition'), ('e93_55_1_h', 'Electoral Act 1993, s 55(1)(h): Death'), ('e93_55_1_i', 'Electoral Act 1993, s 55(1)(i): Mental disorder'), ('c86_18_2', 'Constitution Act 1986, s 18(2): Dissolution of Parliamentary term'), ('c86_17', 'Constitution Act 1986, s 17: Expiry of Parliamentary term'), ('e93_54', 'Electoral Act 1993, s 54: Close of polling day at the next general election')], max_length=16, null=True)),
                ('start_reason', models.CharField(blank=True, choices=[('e93_137', 'Electoral Act 1993, s 137: Supply of list vacancy'), ('ge_elecorate', 'Successful constituency candidate at general election'), ('ge_list', 'Successful list candidate following general election'), ('by_electorate', 'Successful constituency candidate at by-election')], max_length=16, null=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.election')),
                ('electorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wts_app.electorate')),
                ('gazette_notice_election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elected_affiliations', to='wts_app.gazettenotice')),
                ('gazette_notice_vacation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacated_affiliations', to='wts_app.gazettenotice')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.parliament')),
                ('replaced', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='wts_app.parliamentaryaffiliation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinisterialAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('conjunction', models.TextField(blank=True, null=True)),
                ('specialisation', models.TextField(blank=True, null=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('appointment_method', models.CharField(blank=True, choices=[('l', 'Letter'), ('w', 'Warrant'), ('pus w', 'Parliamentary Under-Secretary Warrant')], max_length=5, null=True)),
                ('type', models.CharField(choices=[('p', 'Portfolio'), ('r', 'Responsibility')], default='p', max_length=1)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.ministerialportfolio')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsSet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('results_level', models.CharField(choices=[('national', 'National'), ('electorate', 'Electorate'), ('voting_place', 'Voting place')], max_length=20)),
                ('results_category', models.CharField(choices=[('party_votes', 'Party votes'), ('candidate_votes', 'Candidate votes')], max_length=20)),
                ('informals', models.IntegerField()),
                ('unknowns', models.IntegerField()),
                ('refused', models.IntegerField()),
                ('sample_size', models.IntegerField()),
                ('updated', models.DateTimeField()),
                ('parsed', models.DateTimeField()),
                ('voting_place_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('statistics', models.JSONField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('received', models.DateTimeField(blank=True, null=True)),
                ('electorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wts_app.electionelectorate')),
                ('results_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.electionresultversion')),
                ('voting_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wts_app.electionvotingplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('per_cent', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('list_seats', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('electorate_seats', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_seats', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.electioncandidate')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.electionparty')),
                ('results_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.resultsset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartyBrandHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('colour', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_history', to='wts_app.party')),
            ],
            options={
                'verbose_name_plural': 'Party Name History',
                'ordering': ['-effective_until'],
                'indexes': [models.Index(fields=['party', '-effective_until'], name='wts_app_par_party_i_090d68_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonNameHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_history', to='wts_app.person')),
            ],
            options={
                'verbose_name_plural': 'Person Name History',
                'ordering': ['-effective_until'],
                'indexes': [models.Index(fields=['person', '-effective_until'], name='wts_app_per_person__46753e_idx')],
            },
        ),
    ]
