# Generated by Django 6.0 on 2025-12-15 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliament',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
