# Generated by Django 6.0 on 2025-12-06 12:20

import datetime
import django.db.models.deletion
import uuid
import wts_app.models.documents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightParty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polling_date', models.DateField()),
                ('election_type', models.CharField(choices=[('g', 'General'), ('b', 'By-election')], default='g', max_length=1)),
                ('name', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinisterialPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'People'},
        ),
        migrations.RemoveField(
            model_name='electorate',
            name='code',
        ),
        migrations.AddField(
            model_name='electorate',
            name='electorate_type',
            field=models.CharField(choices=[('general', 'General'), ('maori', 'Māori')], default='general', max_length=10),
        ),
        migrations.AddField(
            model_name='electorate',
            name='region',
            field=models.TextField(default='df'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electorate',
            name='replaced_electorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement', to='wts_app.electorate'),
        ),
        migrations.AddField(
            model_name='electorate',
            name='replacement_electorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced', to='wts_app.electorate'),
        ),
        migrations.AddField(
            model_name='electorate',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='electorate',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('retiring', 'Retiring'), ('new', 'New'), ('former', 'Former'), ('renamed', 'Renamed')], default='current', max_length=10),
        ),
        migrations.AddField(
            model_name='electorate',
            name='valid_from',
            field=models.DateField(default=datetime.datetime(2025, 12, 6, 12, 20, 23, 604402, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electorate',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='electorate',
            name='name',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wts_app.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, null=True, to='wts_app.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, null=True, to='wts_app.category')),
                ('documents', models.ManyToManyField(to='wts_app.document')),
            ],
        ),
        migrations.AddField(
            model_name='parliament',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.election'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.TextField()),
                ('file_description', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('file_type', models.CharField(max_length=255)),
                ('original_link_alive', models.BooleanField(default=True)),
                ('original_link_last_checked', models.DateTimeField(blank=True, null=True)),
                ('original_md5', models.CharField(blank=True, default='', max_length=32)),
                ('stored_md5', models.CharField(blank=True, default='', max_length=32)),
                ('file', models.FileField(storage=wts_app.models.documents.select_storage, upload_to=wts_app.models.documents.upload_to)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('copyright_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_files', to='wts_app.copyrightparty')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='wts_app.document')),
                ('licence_grantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licensed_files', to='wts_app.copyrightparty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='wts_app.file'),
        ),
        migrations.CreateModel(
            name='GazetteNotice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=255)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gazette_notices', to='wts_app.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('licence_url', models.URLField(blank=True, null=True)),
                ('parent_licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.licence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='file',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.licence'),
        ),
        migrations.CreateModel(
            name='MinisterialAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('conjunction', models.TextField(blank=True, null=True)),
                ('specialisation', models.TextField(blank=True, null=True)),
                ('appointment_method', models.CharField(blank=True, choices=[('l', 'Letter'), ('w', 'Warrant'), ('pus w', 'Parliamentary Under-Secretary Warrant')], max_length=5, null=True)),
                ('type', models.CharField(choices=[('p', 'Portfolio'), ('r', 'Responsibility')], default='p', max_length=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.person')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.ministerialportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryAffiliation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elected_date', models.DateField(blank=True, null=True)),
                ('sworn_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fallback_electorate_slug', models.TextField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('e93_55_1_a', 'Electoral Act 1993, s 55(1)(a): Non-attendance'), ('e93_55_1_b', 'Electoral Act 1993, s 55(1)(b): Allegiance to foreign state'), ('e93_55_1_c', 'Electoral Act 1993, s 55(1)(c): Subject or citizen of foreign state'), ('e93_55_1_ca', 'Electoral Act 1993, s 55(1)(ca): Cessation of New Zealand citizenship'), ('e93_55_1_cb_i', 'Electoral Act 1993, s 55(1)(cb)(i): Candidate in foreign Parliamentary election'), ('e93_55_1_cb_ii', 'Electoral Act 1993, s 55(1)(cb)(ii): Candidate in foreign governing body election'), ('e93_55_1_d', 'Electoral Act 1993, s 55(1)(d): Serious conviction or corruption'), ('e93_55_1_e', 'Electoral Act 1993, s 55(1)(e): Became public servant'), ('e93_55_1_ea', 'Electoral Act 1993, s 55(1)(ea): Appointed as electoral official'), ('e93_55_1_f', 'Electoral Act 1993, s 55(1)(f): Resignation'), ('e93_55_1_f_by', 'Electoral Act 1993, s 55(1)(f): Resignation (successful constituency candidate at by-election)'), ('e93_55_1_fa', 'Electoral Act 1993, ss 55(1)(fa) and 55A: Cessation of party membership'), ('e93_55_1_g', 'Electoral Act 1993, s 55(1)(g): Election voided on petition'), ('e93_55_1_h', 'Electoral Act 1993, s 55(1)(h): Death'), ('e93_55_1_i', 'Electoral Act 1993, s 55(1)(i): Mental disorder'), ('c86_18_2', 'Constitution Act 1986, s 18(2): Dissolution of Parliamentary term'), ('c86_17', 'Constitution Act 1986, s 17: Expiry of Parliamentary term'), ('e93_54', 'Electoral Act 1993, s 54: Close of polling day at the next general election')], max_length=16, null=True)),
                ('start_reason', models.CharField(blank=True, choices=[('e93_137', 'Electoral Act 1993, s 137: Supply of list vacancy'), ('ge_elecorate', 'Successful constituency candidate at general election'), ('ge_list', 'Successful list candidate following general election'), ('by_electorate', 'Successful constituency candidate at by-election')], max_length=16, null=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.election')),
                ('electorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wts_app.electorate')),
                ('gazette_notice_election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elected_affiliations', to='wts_app.gazettenotice')),
                ('gazette_notice_vacation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacated_affiliations', to='wts_app.gazettenotice')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.parliament')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.person')),
                ('replaced', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='wts_app.parliamentaryaffiliation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartyAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.party')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.person')),
            ],
        ),
    ]
