# Generated by Django 6.0 on 2025-12-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0002_copyrightparty_election_ministerialportfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(to='wts_app.category'),
        ),
        migrations.AlterField(
            model_name='documentcollection',
            name='categories',
            field=models.ManyToManyField(to='wts_app.category'),
        ),
    ]
