# Generated by Django 6.0 on 2025-12-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0003_alter_document_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='copyrightparty',
            options={'verbose_name_plural': 'Copyright Parties'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
