# Generated by Django 6.0 on 2025-12-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0004_documentcollection_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='deregistered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='registered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='registration_dates_precise',
            field=models.BooleanField(default=False),
        ),
    ]
