# Generated by Django 6.0 on 2025-12-07 00:18

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0004_alter_category_options_alter_copyrightparty_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copyrightparty',
            options={'verbose_name_plural': 'Copyright parties'},
        ),
        migrations.AddField(
            model_name='election',
            name='gazette_notices',
            field=models.ManyToManyField(blank=True, to='wts_app.gazettenotice'),
        ),
        migrations.AddField(
            model_name='election',
            name='polls_close',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 7, 0, 18, 13, 158702, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ElectorateBoundarySet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electorate_boundary_sets', to='wts_app.document')),
                ('gazette_notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.gazettenotice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectorateBoundary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('electorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.electorate')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electorate_boundaries', to='wts_app.file')),
                ('boundary_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.electorateboundaryset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='election',
            name='boundary_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.electorateboundaryset'),
        ),
    ]
