# Generated by Django 6.0 on 2025-12-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0005_party_deregistered_date_party_is_registered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gazettenotice',
            options={'ordering': ['-file__published_date']},
        ),
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('g', 'General'), ('b', 'By-election'), ('general', 'General'), ('by-election', 'By-election')], default='general', max_length=20),
        ),
    ]
