# Generated by Django 6.0 on 2025-12-07 02:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0005_alter_copyrightparty_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electorate',
            old_name='replaced_electorate',
            new_name='replaced',
        ),
        migrations.RemoveField(
            model_name='electorate',
            name='replacement_electorate',
        ),
        migrations.AlterField(
            model_name='gazettenotice',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gazette_notices', to='wts_app.file'),
        ),
        migrations.AlterField(
            model_name='gazettenotice',
            name='number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ElectionResultVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.election')),
            ],
            options={
                'unique_together': {('election', 'slug')},
            },
        ),
    ]
