# Generated by Django 6.0 on 2025-12-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0006_alter_gazettenotice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('general', 'General'), ('by-election', 'By-election')], default='general', max_length=20),
        ),
    ]
