# Generated by Django 6.0 on 2025-12-15 07:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0007_alter_election_election_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInterestSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_at', models.DateField()),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.document')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialInterest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest_type', models.CharField(choices=[('1', 'Company directorships and controlling interests'), ('2', 'Other companies and business entities'), ('3', 'Employment'), ('4', 'Beneficial interests in, and trusteeships of, trusts'), ('5', 'Organisations and trusts seeking Government funding'), ('6', 'Real property'), ('7', 'Retirement schemes'), ('8', 'Managed investment schemes'), ('9', 'Debtors'), ('10', 'Creditors'), ('11', 'Overseas travel costs'), ('12', 'Gifts'), ('13', 'Discharged debts'), ('14', 'Payments for activities')], max_length=2)),
                ('description', models.TextField()),
                ('nzbn_entity_name', models.TextField(blank=True, null=True)),
                ('nzbn', models.TextField(blank=True, null=True)),
                ('nzbn_entity_type_code', models.TextField(blank=True, null=True)),
                ('nzbn_entity_type_desc', models.TextField(blank=True, null=True)),
                ('nzbn_entity_classifications', models.TextField(blank=True, null=True)),
                ('nzbn_entity_classifications_descs', models.TextField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.financialinterestsnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
