# Generated by Django 6.0 on 2025-12-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0008_financialinterestsnapshot_financialinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
    ]
