# Generated by Django 6.0 on 2025-12-16 06:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0009_remove_document_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cached_colour',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='person',
            name='cached_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
