# Generated by Django 6.0 on 2025-12-16 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0010_person_cached_colour_person_cached_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electorate',
            name='replaced',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement', to='wts_app.electorate'),
        ),
    ]
