# Generated by Django 6.0 on 2025-12-20 23:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0011_alter_electorate_replaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_persistent', models.BooleanField(default=False, help_text='Whether the banner can be dismissed by the user')),
                ('display_start', models.DateTimeField(help_text='Start of the period for which the banner is shown')),
                ('display_end', models.DateTimeField(help_text='End of the period for which the banner is shown')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('url_type', models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], help_text='Type of URL (internal or external)', max_length=20, null=True)),
                ('url_behaviour', models.CharField(blank=True, choices=[('new', 'New Window'), ('same', 'Same Window')], help_text='How the URL should open (new window or same window)', max_length=20, null=True)),
                ('url', models.TextField(blank=True, help_text='URL (may be a relative path, no domain or protocol required)', null=True)),
            ],
            options={
                'ordering': ['-display_start'],
            },
        ),
    ]
