# Generated by Django 6.0 on 2025-12-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0012_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='display_end',
            field=models.DateTimeField(blank=True, help_text='End of the period for which the banner is shown (null means indefinite)', null=True),
        ),
    ]
