# Generated by Django 6.0 on 2025-12-21 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0013_alter_banner_display_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url_behaviour',
            field=models.CharField(blank=True, choices=[('new', 'New window'), ('same', 'Same window')], help_text='How the URL should open (new window or same window)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parliament',
            name='election',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.election'),
        ),
    ]
