# Generated by Django 6.0 on 2025-12-21 01:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0014_alter_banner_url_behaviour_alter_parliament_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('parliament_document_id', models.TextField(blank=True, null=True)),
                ('parliament_api_id', models.TextField(blank=True, null=True)),
                ('parliament_api_status', models.TextField(blank=True, null=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('ref', models.TextField(blank=True, null=True)),
                ('bill_type', models.CharField(blank=True, choices=[('members', "Member's bill"), ('government', 'Government bill'), ('private', 'Private bill'), ('local', 'Local bill')], max_length=10, null=True)),
                ('voting_methods', models.CharField(choices=[('personal', 'Personal votes only'), ('party', 'Party votes only'), ('mixed', 'Mixed voting'), ('unknown', 'Unknown')], default='unknown', max_length=8)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('in_progress', 'In progress'), ('defeated', 'Defeated'), ('withdrawn', 'Withdrawn'), ('passed', 'Passed'), ('enacted', 'Enacted'), ('divided', 'Divided'), ('lapsed', 'Lapsed'), ('unknown_not_current', 'Unknown / Not Current'), ('discharged', 'Discharged')], default='unknown', max_length=19)),
                ('select_committee_name', models.TextField(blank=True, null=True)),
                ('select_committee_status', models.TextField(blank=True, null=True)),
                ('introduction_date', models.DateField(blank=True, null=True)),
                ('first_reading_date', models.DateField(blank=True, null=True)),
                ('submissions_due_date', models.DateField(blank=True, null=True)),
                ('report_back_date', models.DateField(blank=True, null=True)),
                ('second_reading_date', models.DateField(blank=True, null=True)),
                ('whole_house_date', models.DateField(blank=True, null=True)),
                ('third_reading_date', models.DateField(blank=True, null=True)),
                ('royal_assent_date', models.DateField(blank=True, null=True)),
                ('withdrawn_date', models.DateField(blank=True, null=True)),
                ('defeated_date', models.DateField(blank=True, null=True)),
                ('defeated_reading', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('lapsed_date', models.DateField(blank=True, null=True)),
                ('act_name', models.TextField(blank=True, null=True)),
                ('act_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('act_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1840)])),
                ('legislation_url', models.URLField(blank=True, null=True)),
                ('original_api_response', models.JSONField(blank=True, null=True)),
                ('is_divided', models.BooleanField(default=False)),
                ('extended_sittings_used', models.BooleanField(default=False)),
                ('urgency_used', models.BooleanField(default=False)),
                ('flag_scraped_under_v2', models.BooleanField(default=False)),
                ('flag_enacted_but_missing_assent_number', models.BooleanField(default=False)),
                ('child_bills', models.ManyToManyField(blank=True, related_name='parent_bills', to='wts_app.bill')),
                ('parliaments', models.ManyToManyField(related_name='bills', to='wts_app.parliament')),
                ('people_responsible', models.ManyToManyField(related_name='bills', to='wts_app.person')),
            ],
            options={
                'verbose_name_plural': 'Bills',
                'ordering': ['-introduction_date'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('parliament_document_id', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('reading', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('ayes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('noes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('abstentions', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('import_method', models.CharField(choices=[('parse', 'Hansard parser'), ('api', 'Parliament API'), ('manual', 'Manual'), ('ai', 'AI assisted')], default='parse', max_length=10)),
                ('motion_agreed', models.BooleanField(default=False)),
                ('outcome_text', models.TextField(blank=True, null=True)),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('vote_type', models.CharField(blank=True, choices=[('party', 'Party vote'), ('personal', 'Personal vote'), ('voice', 'Voice vote')], max_length=8, null=True)),
                ('contains_split_party_votes', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.bill')),
            ],
            options={
                'verbose_name_plural': 'Votes',
                'ordering': ['-date'],
                'unique_together': {('bill', 'reading')},
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_proxy_vote', models.BooleanField(default=False)),
                ('is_split_party_vote', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('aye', 'Aye'), ('no', 'No'), ('abstention', 'Abstention'), ('absent', 'Absent')], max_length=10)),
                ('contribution', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wts_app.party')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wts_app.person')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.vote')),
            ],
            options={
                'verbose_name_plural': 'Vote records',
                'ordering': ['-vote__date'],
                'unique_together': {('vote', 'person')},
            },
        ),
    ]
