# Generated by Django 6.0 on 2025-12-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0015_bill_vote_voterecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='legislation_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
