# Generated by Django 6.0 on 2025-12-21 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0016_alter_bill_legislation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='absentees',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='hansard_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
