# Generated by Django 6.0 on 2025-12-23 01:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0017_vote_absentees_vote_hansard_status_vote_retrieved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncandidate',
            name='electorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.electionelectorate'),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='firebase_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='list_pos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.electionparty'),
        ),
        migrations.AddField(
            model_name='electionelectorate',
            name='firebase_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electionparty',
            name='firebase_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electionresultversion',
            name='access_mode',
            field=models.CharField(choices=[('api', 'API'), ('firebase', 'Firebase')], default='api', max_length=20),
        ),
        migrations.AddField(
            model_name='electionresultversion',
            name='firebase_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electionvotingplace',
            name='firebase_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persistentvotingplace',
            name='firebase_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='firebase_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsset',
            name='firebase_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='electioncandidate',
            index=models.Index(fields=['results_version'], name='wts_app_ele_results_3e5060_idx'),
        ),
        migrations.AddIndex(
            model_name='electionelectorate',
            index=models.Index(fields=['results_version'], name='wts_app_ele_results_1f6e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='electionparty',
            index=models.Index(fields=['results_version'], name='wts_app_ele_results_b8545e_idx'),
        ),
        migrations.AddIndex(
            model_name='electionvotingplace',
            index=models.Index(fields=['results_version'], name='wts_app_ele_results_40bc96_idx'),
        ),
        migrations.AddIndex(
            model_name='resultsset',
            index=models.Index(fields=['results_version'], name='wts_app_res_results_d6319c_idx'),
        ),
    ]
