# Generated by Django 6.0 on 2025-12-23 01:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0018_electioncandidate_electorate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('firebase_id', models.TextField(blank=True, null=True)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
