# Generated by Django 6.0 on 2025-12-23 01:53

import colorfield.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0019_persistentcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionparty',
            name='abbreviation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electionparty',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electionparty',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electionparty',
            name='short_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PersistentParty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_id', models.TextField(blank=True, null=True)),
                ('abbreviation', models.TextField(blank=True, null=True)),
                ('colour', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('party', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.party')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
