# Generated by Django 6.0 on 2025-12-23 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0021_electioncandidate_unique_results_version_candidate_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionparty',
            name='party',
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='persistent_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.persistentcandidate'),
        ),
        migrations.AddField(
            model_name='electionparty',
            name='persistent_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.persistentparty'),
        ),
        migrations.AddField(
            model_name='electionvotingplace',
            name='persistent_voting_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wts_app.persistentvotingplace'),
        ),
    ]
