# Generated by Django 6.0 on 2025-12-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0022_remove_electionparty_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioncandidate',
            name='firebase_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='electionelectorate',
            name='firebase_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='electionparty',
            name='firebase_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='electionresultversion',
            name='firebase_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='electionvotingplace',
            name='firebase_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persistentparty',
            name='firebase_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persistentvotingplace',
            name='firebase_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='firebase_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='resultsset',
            name='firebase_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
