# Generated by Django 6.0 on 2025-12-26 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0024_rename_voting_place_number_resultsset_result_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterecord',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='wts_app.vote'),
        ),
    ]
