# Generated by Django 6.0 on 2025-12-27 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0025_alter_voterecord_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardReconciliation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_reconciliations', to='wts_app.file')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_reconciliations', to='wts_app.person')),
            ],
            options={
                'verbose_name_plural': 'Credit card reconciliations',
                'ordering': ['-start_date', '-end_date'],
            },
        ),
    ]
