# Generated by Django 6.0 on 2025-12-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0026_creditcardreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardreconciliation',
            name='hidden_from_timeline',
            field=models.BooleanField(default=True),
        ),
    ]
