# Generated by Django 6.0 on 2025-12-29 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0028_alter_creditcardreconciliation_hidden_from_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='wts_app.bill'),
        ),
    ]
