# Generated by Django 6.0 on 2025-12-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0029_alter_vote_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
