# Generated by Django 6.0 on 2026-01-17 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wts_app", "0030_bill_last_activity_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCardExpense",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("merchant_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("amount_nzd", models.DecimalField(decimal_places=2, max_digits=12)),
                ("original_currency_code", models.CharField(max_length=3)),
                ("original_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="wts_app.creditcardreconciliation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Credit card expenses",
                "ordering": ["-date", "merchant_name"],
            },
        ),
        migrations.CreateModel(
            name="GeminiBatchJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("processor", models.CharField(max_length=100)),
                ("requested_model", models.CharField(max_length=255)),
                ("resolved_model", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partially succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("cancelling", "Cancelling"),
                            ("paused", "Paused"),
                            ("expired", "Expired"),
                            ("unknown", "Unknown"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("batch_name", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=255, null=True)),
                ("input_file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("output_file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("raw_request", models.JSONField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="gemini_job_status_idx"),
                    models.Index(fields=["processor", "status"], name="gemini_job_proc_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GeminiBatchItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("output_index", models.PositiveIntegerField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("object_id", models.CharField(max_length=64)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="wts_app.geminibatchjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["content_type", "object_id"], name="gemini_item_content_idx"),
                    models.Index(fields=["job", "status"], name="gemini_item_job_status_idx"),
                ],
            },
        ),
    ]
