# Generated by Django 6.0 on 2026-01-08 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0030_bill_last_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionDonationReturn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden_from_timeline', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_donation_returns', to='wts_app.persistentcandidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_donation_returns', to='wts_app.election')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_donation_returns', to='wts_app.file')),
            ],
            options={
                'verbose_name_plural': 'Election donation returns',
                'ordering': ['-election__polling_date'],
            },
        ),
    ]
