# Generated by Django 6.0 on 2026-01-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wts_app", "0031_gemini_batches_and_expenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcardreconciliation",
            name="concerns",
            field=models.TextField(blank=True, null=True),
        ),
    ]
