# Generated by Django 6.0 on 2026-01-18 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0031_electiondonationreturn'),
        ('wts_app', '0031_gemini_batches_and_expenses'),
    ]

    operations = [
    ]
