# Generated by Django 6.0 on 2026-01-18 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0032_creditcardreconciliation_concerns'),
        ('wts_app', '0032_merge_20260118_1302'),
    ]

    operations = [
    ]
