# Generated by Django 6.0 on 2026-04-09 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0034_rename_party_color_to_colour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parliamentaryaffiliation',
            options={'ordering': ['parliament__number', 'person__last_name']},
        ),
        migrations.AlterModelOptions(
            name='persistentcandidate',
            options={'ordering': ['display_name']},
        ),
        migrations.CreateModel(
            name='PartyLeader',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.party')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wts_app.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
