# Generated by Django 6.0 on 2026-01-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0034_twitter_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwitterUser',
            new_name='XUser',
        ),
        migrations.RenameModel(
            old_name='TwitterMetrics',
            new_name='XMetrics',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='twitter_user',
            new_name='x_user',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='twitter_user',
            new_name='x_user',
        ),
    ]
