# Generated by Django 6.0 on 2026-04-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0038_feedback'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parliamentaryaffiliation',
            index=models.Index(fields=['-elected_date'], name='elected_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='parliamentaryaffiliation',
            index=models.Index(fields=['-sworn_date'], name='sworn_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='parliamentaryaffiliation',
            index=models.Index(fields=['-end_date'], name='end_date_desc_idx'),
        ),
    ]
