# Generated by Django 6.0 on 2026-04-25 07:40

from django.db import migrations, models

from ._user_model import create_user_model


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wts_app", "0039_parliamentaryaffiliation_elected_date_desc_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parliamentaryaffiliation',
            new_name='parl_aff_elected_date_desc_idx',
            old_name='elected_date_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='parliamentaryaffiliation',
            new_name='parl_aff_sworn_date_desc_idx',
            old_name='sworn_date_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='parliamentaryaffiliation',
            new_name='parl_aff_end_date_desc_idx',
            old_name='end_date_desc_idx',
        ),
        migrations.AddIndex(
            model_name='parliamentaryaffiliation',
            index=models.Index(fields=['person'], name='parl_aff_person_idx'),
        ),
        migrations.AddIndex(
            model_name='partyaffiliation',
            index=models.Index(fields=['-start_date'], name='party_aff_start_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='partyaffiliation',
            index=models.Index(fields=['-end_date'], name='party_aff_end_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='partyaffiliation',
            index=models.Index(fields=['person'], name='party_aff_person_idx'),
        ),
        migrations.AddIndex(
            model_name='partyaffiliation',
            index=models.Index(fields=['party'], name='party_aff_party_idx'),
        ),
        # Register the custom user model in migration state only. The table is
        # created in 0041_user so admin.LogEntry can resolve AUTH_USER_MODEL
        # before that migration runs on databases that already had contrib.auth.
        migrations.SeparateDatabaseAndState(
            state_operations=[create_user_model()],
            database_operations=[],
        ),
    ]
