# Generated by Django 6.0 on 2026-05-25 08:52

import django.db.models.deletion
import uuid
import wts_app.models.workbooks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0045_workbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbookFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=wts_app.models.workbooks.select_storage, upload_to=wts_app.models.workbooks.upload_to)),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='wts_app.workbook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
