# Generated by Django 6.0 on 2026-05-25 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0046_workbookfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workbooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
