# Generated by Django 6.0 on 2026-05-25 10:38

import wts_app.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0047_alter_workbook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=wts_app.models.user.select_storage, upload_to=wts_app.models.user.upload_to),
        ),
    ]
