# Generated by Django 6.0 on 2026-05-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0054_workbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('workbook_created', 'Workbook created'), ('preprocessed', 'Preprocessed'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=32),
        ),
    ]
