# Generated by Django 6.0 on 2026-05-31 04:51

import django.core.validators
import django.db.models.deletion
import uuid
import wts_app.models.hansard
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0055_alter_systemevent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HansardDaily',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_date', models.DateField(unique=True)),
                ('transcript_file', models.FileField(storage=wts_app.models.hansard.HansardDaily._select_storage, upload_to=wts_app.models.hansard.HansardDaily._upload_to)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('daily_content', models.TextField(blank=True, null=True)),
                ('daily_id', models.CharField(blank=True, max_length=36, null=True)),
                ('daily_parliament_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_volume_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_progress', models.CharField(blank=True, choices=[('Draft', 'Complete'), ('Corrected', 'Corrected'), ('Final', 'Final'), ('__other__', '__other__')], max_length=10, null=True)),
                ('daily_title', models.TextField(blank=True, null=True)),
                ('daily_subtitle', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HansardSearchResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_id', models.CharField(max_length=36, unique=True)),
                ('result_title', models.TextField(blank=True, null=True)),
                ('result_subtitle', models.TextField(blank=True, null=True)),
                ('result_volume_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('result_sitting_date', models.DateField(blank=True, null=True)),
                ('result_document_type', models.CharField(blank=True, choices=[('DebateItem', 'DebateItem'), ('__other__', '__other__')], max_length=10, null=True)),
                ('result_document_subtype', models.CharField(blank=True, choices=[('Debate', 'Debate'), ('Question', 'Question'), ('Speech', 'Speech'), ('Vote', 'Vote'), ('__other__', '__other__')], max_length=10, null=True)),
                ('result_progress', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Corrected', 'Corrected'), ('Final', 'Final'), ('__other__', '__other__')], max_length=10, null=True)),
                ('result_member_id', models.CharField(blank=True, max_length=36, null=True)),
                ('result_member_name', models.TextField(blank=True, null=True)),
                ('result_sort_index', models.IntegerField(blank=True, null=True)),
                ('result_portfolio', models.TextField(blank=True, null=True)),
                ('result_parliament_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('result_parent_result_id', models.CharField(blank=True, max_length=36, null=True)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HansardDebate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debate_id', models.CharField(blank=True, max_length=36, null=True)),
                ('debate_title', models.TextField(blank=True, null=True)),
                ('debate_content', models.TextField(blank=True, null=True)),
                ('debate_subtitle', models.TextField(blank=True, null=True)),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='wts_app.hansarddaily')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HansardBillAssocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assocation_id', models.CharField(blank=True, max_length=36, null=True)),
                ('bill_title', models.TextField(blank=True, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=36, null=True)),
                ('matched_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hansard_bill_associations', to='wts_app.bill')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_associations', to='wts_app.hansarddebate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HansardItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(blank=True, choices=[('Question', 'Question'), ('Speech', 'Speech'), ('Vote', 'Vote'), ('__other__', '__other__')], max_length=10, null=True)),
                ('item_member_id', models.CharField(blank=True, max_length=36, null=True)),
                ('item_electorate', models.TextField(blank=True, null=True)),
                ('item_start_time', models.DateTimeField(blank=True, null=True)),
                ('item_member_name', models.TextField(blank=True, null=True)),
                ('item_id', models.CharField(blank=True, max_length=36, null=True)),
                ('item_title', models.TextField(blank=True, null=True)),
                ('item_content', models.TextField(blank=True, null=True)),
                ('item_subtitle', models.TextField(blank=True, null=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wts_app.hansarddebate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
