# Generated by Django 6.0 on 2026-05-31 06:12

import wts_app.models.hansard
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0056_hansarddaily_hansardsearchresult_hansarddebate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hansarddaily',
            name='style_file',
            field=models.FileField(default='1', storage=wts_app.models.hansard.HansardDaily._select_storage, upload_to=wts_app.models.hansard.HansardDaily._upload_to_style),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hansarddaily',
            name='daily_progress',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Corrected', 'Corrected'), ('Final', 'Final'), ('__other__', '__other__')], max_length=10, null=True),
        ),
    ]
