# Generated by Django 6.0 on 2026-05-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0057_hansarddaily_style_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='parliament_api_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
