# Generated by Django 6.0 on 2026-05-31 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0058_person_parliament_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hansarditem',
            name='matched_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hansard_items', to='wts_app.person'),
        ),
        migrations.AddField(
            model_name='hansardsearchresult',
            name='matched_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hansard_search_results', to='wts_app.person'),
        ),
        migrations.AddField(
            model_name='vote',
            name='hansard_api_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
