# Generated by Django 6.0 on 2026-05-31 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wts_app', '0059_hansarditem_matched_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoUpdate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('started', 'Started')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('updated_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_updates_by_object', to='contenttypes.contenttype')),
                ('updated_model_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_updates_by_model', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
