# Generated by Django 6.0 on 2026-05-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0060_autoupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoupdate',
            name='updated_model_content_type',
        ),
    ]
