# Generated by Django 6.0 on 2026-05-31 22:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0061_remove_autoupdate_updated_model_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteStub',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reading', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_stubs', to='wts_app.bill')),
                ('hansard_search_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_stubs', to='wts_app.hansardsearchresult')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
