# Generated by Django 6.0 on 2026-05-31 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0062_votestub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votestub',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Vote stubs'},
        ),
        migrations.AlterUniqueTogether(
            name='votestub',
            unique_together={('reading', 'bill')},
        ),
    ]
