# Generated by Django 6.0 on 2026-06-01 02:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0063_alter_votestub_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('person', 'Person'), ('party', 'Party'), ('electorate', 'Electorate'), ('bill', 'Bill'), ('vote', 'Vote'), ('hansard', 'Hansard'), ('gazette', 'Gazette')], max_length=255)),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='site_search',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='wts_app.sitesearch'),
        ),
        migrations.AddField(
            model_name='electorate',
            name='site_search',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electorate', to='wts_app.sitesearch'),
        ),
        migrations.AddField(
            model_name='party',
            name='site_search',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to='wts_app.sitesearch'),
        ),
        migrations.AddField(
            model_name='person',
            name='site_search',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='wts_app.sitesearch'),
        ),
    ]
