# Generated by Django 6.0 on 2026-06-01 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0064_sitesearch_bill_site_search_electorate_site_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='stub',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote', to='wts_app.votestub'),
        ),
    ]
