# Generated by Django 6.0 on 2026-08-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wts_app', '0066_election_result_version_firebase_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionvotingplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electionvotingplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persistentvotingplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persistentvotingplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
